### ISSUE TITLE
IllegalArgumentException Version 9.1.0-Alpha3

### ISSUE THREAD

**Issue by CreeperboyMCVN** [MrUniverse44/PixelMOTD3#1]
This error keeps spamming in bungeecord console, please help

```
04:10:46 [WARNING] Error dispatching event ProxyPingEvent(connection=[/171.242.232.228:55292] <-> InitialHandler, response=ServerPing(version=ServerPing.Protocol(name=BungeeCord 1.8.x-1.17.x, protocol=340), players=ServerPing.Players(max=1000, online=3, sample=null), description=§f§f §f §f §f §f §c§l§k|||§a §a§lＭＩＮＥＶＩＥＴ.ＣＯＭ§a 1.8.x §6▲§4 1.17.x §c§l§k|||
§6§lFactionRPG §3| §9§lVillageDefense §3| §c§lCreative§c - và hơn nữa!, modinfo=ServerPing.ModInfo(type=FML, modList=[]))) to listener dev.mruniverse.pixelmotd.bungeecord.listeners.PingListener@b889cb6
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Unknown Source)
	at dev.mruniverse.pixelmotd.bungeecord.listeners.PingBuilder.getMotd(PingBuilder.java:44)
	at dev.mruniverse.pixelmotd.bungeecord.listeners.PingBuilder.execute(PingBuilder.java:48)
	at dev.mruniverse.pixelmotd.bungeecord.listeners.PingListener.onPing(PingListener.java:78)
	at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:266)
	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:242)
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:275)
	at net.md_5.bungee.protocol.packet.StatusRequest.handle(StatusRequest.java:29)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:514)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)
	```

**Comment by MrUniverse44** [comment]
please send your motds.yml file and your server version

**Comment by CreeperboyMCVN** [comment]
BungeeCord 1.17 build 1608
```yml
#   _____ _          _ __  __  ____ _______ _____
#   |  __ (_)        | |  \/  |/ __ \__   __|  __ \
#   | |__) |__  _____| | \  / | |  | | | |  | |  | |
#   |  ___/ \ \/ / _ \ | |\/| | |  | | | |  | |  | |
#   | |   | |>  <  __/ | |  | | |__| | | |  | |__| |
#   |_|   |_/_/\_\___|_|_|  |_|\____/  |_|  |_____/
#
#   Using version 9.0.0-SNAPSHOT
#   Author: MrUniverse44
#   SpigotMC Link: https://www.spigotmc.org/resources/37177/
#
normal:
  settings:
    icon: true
    # Custom Players Settings on online player count.
    custom-online:
      # Enable this option
      enable: false
      # Modes:
      # ADD-<number>,REMOVE-<number>, VALUES, ADD_MIDDLE, REMOVE_MIDDLE, EQUALS
      mode: 'EQUALS'
      # List of values:
      values:
        - 300
    # Custom Players Settings on max player count.
    custom-max:
      # Enable this option
      enable: false
      # Modes:
      # ADD-<number>,REMOVE-<number>, VALUES, ADD_MIDDLE, REMOVE_MIDDLE, EQUALS
      mode: 'VALUES'
      # List of values:
      values:
        - 10000
    # Custom protocol settings on player count.
    custom-protocol:
      # Enable custom protocol.
      enable: false
      # If you want to change protocol when a player tries
      # to join on a incompatible version, keep it false.
      # Instead will display protocol name always.
      change-protocol-version:
        # Toggle this option
        toggle: true
        # Value of this protocol, protocol list: https://minecraft.fandom.com/wiki/Protocol_version
        # Show Incompatible version using '-1'
        value: 'EQUALS'
      # Custom protocol name to set if enabled.
      name: PixelMOTD
  #
  # MOTD FEATURE
  # You can add many motds as you want.
  # But always should be in this format:
  #
  #  first: # <--- CHANGE MOTD NAME, don't repeat it
  #    line-1: "message 1"
  #    line-2: "message 2"
  #    with-hex:
  #      enable: true
  #      line-1: "message 1"
  #      line-2: "message 2"
  #
  motds:
    first: # <-- Avoid duplication names on this if you want to add more.
      
      line-1: "         &c»»»&a &lＭＩＮＥＶＩＥＴ.ＣＯＭ&a 1.8.x &6➫&4 1.17.x &c«««"
      line-2: "                   &a『 &2&lFactionRPG Beta! &a』"
      # ====================================================
      # HEX COLORS SUPPORT MISSING AT THE MOMENT.
      # ====================================================

      # Here you can use hex colors, if you don't need this
      # feature, you can disable this.
      # Only shows on 1.16 this motd, even if it doesn't have HEX colors.
      with-hex:
        enable: false
        line-1: "&b&lPixelMOTD &7| Using &e1.16+ &7display!"
        line-2: "&fEnjoy our great Network!"
      # Custom hover PER MOTD feature.
      # NOTE: Variables not supported right now.
      hover:
        toggle: true
        # Show players of an specific world in the hover.
        message:
          - "   &a&lＭＩＮＥＶＩＥＴ.ＣＯＭ"
          - "&7&m----------------------------"
          - "&aWebsite: &7&nwww.mineviet.com"
          - "&aForum: &7&nforum.mineviet.com"
          - "&aDiscord: &7&ndsc.gg/minevietmcsv"
          - "&7&m----------------------------"
      # Use custom icon for your motd
      # Can set it on plugins/PixelMOTD/icons/normal/
      # MUST BE 64x64 icon.
      custom-icon:
        # Enable per-motd icon
        enable: false
        # If this option is enabled the plugin will create a new folder called "<mode>-<motdName>"
        # If you don't want use only 1 icon and you want more icons, you can use "RANDOM" in the name.
        name: "icon.png"
    another: # <-- Avoid duplication names on this if you want to add more.
      line-1: "         &c»»»&a &lＭＩＮＥＶＩＥＴ.ＣＯＭ&a 1.8.x &6➫&4 1.17.x &c«««"
      line-2: "                   &a『 &2&lFactionRPG Beta! &a』"
      # ====================================================
      # HEX COLORS SUPPORT MISSING AT THE MOMENT.
      # ====================================================

      # Here you can use hex colors, if you don't need this
      # feature, you can disable this.
      # Only shows on 1.16 this motd, even if it doesn't have HEX colors.
      with-hex:
        enable: false
        line-1: "&b&lPixelMOTD &7| Using &e1.16+ &7display!"
        line-2: "&fEnjoy our great Network!"
      # Custom hover PER MOTD feature.
      # NOTE: Variables not supported right now.
      hover:
        toggle: true
        # Show players of an specific world in the hover.
        message:
          - "   &a&lＭＩＮＥＶＩＥＴ.ＣＯＭ"
          - "&7&m----------------------------"
          - "&aWebsite: &7&nwww.mineviet.com"
          - "&aForum: &7&nforum.mineviet.com"
          - "&aDiscord: &7&ndsc.gg/minevietmcsv"
          - "&7&m----------------------------"
      # Use custom icon for your motd
      # Can set it on plugins/PixelMOTD/icons/normal/
      # MUST BE 64x64 icon.
      custom-icon:
        # Enable per-motd icon
        enable: false
        # If this option is enabled the plugin will create a new folder called "<mode>-<motdName>"
        # If you don't want use only 1 icon and you want more icons, you can use "RANDOM" in the name.
        name: "icon.png"
whitelist:
  # Use custom icon for Whitelist MOTDs
  # Can set it on plugins/PixelMOTD/icons/whitelist/whitelist.png
  # MUST BE 64x64 icon.
  settings:
    icon: true
    # Custom Players Settings on online player count.
    custom-online:
      # Enable this option
      enable: false
      # Modes:
      # ADD-<number>,REMOVE-<number>, VALUES, ADD_MIDDLE, REMOVE_MIDDLE, EQUALS
      mode: 'ADD-450'
      # List of values:
      values:
        - 300
    # Custom Players Settings on max player count.
    custom-max:
      # Enable this option
      enable: false
      # Modes:
      # ADD-<number>,REMOVE-<number>, VALUES, ADD_MIDDLE, REMOVE_MIDDLE, EQUALS
      mode: 'EQUALS'
      # List of values:
      values:
        - 10000
    # Custom protocol settings on player count.
    custom-protocol:
      # Enable custom protocol.
      enable: true
      # If you want to change protocol when a player tries
      # to join on a incompatible version, keep it false.
      # Instead will display protocol name always.
      change-protocol-version:
        # Toggle this option
        toggle: true
        # Value of this protocol, protocol list: https://minecraft.fandom.com/wiki/Protocol_version
        # Show Incompatible version using '-1' (this is by default in whitelist motd)
        value: '-1'
      # Custom protocol name to set if enabled.
      name: Whitelist PixelMOTD
  #
  # MOTD FEATURE
  # You can add many motds as you want.
  # But always should be in this format:
  #
  #  first: # <--- CHANGE MOTD NAME, don't repeat it
  #    line-1: "message 1"
  #    line-2: "message 2"
  #    with-hex:
  #      enable: true
  #      line-1: "message 1"
  #      line-2: "message 2"
  #
  motds:
    first:
      line-1: "         &c&l&k|||&a &lＭＩＮＥＶＩＥＴ.ＣＯＭ&a 1.8.x &6▲&4 1.17.x &c&l&k|||"
      line-2: "&cMáy chủ bảo trì! Vui lòng quay lại sau!"
      # ====================================================
      # HEX COLORS SUPPORT MISSING AT THE MOMENT.
      # ====================================================

      # Here you can use hex colors, if you don't need this
      # feature, you can disable this.
      # Only shows on 1.16 this motd, even if it doesn't have HEX colors.
      with-hex:
        enable: false
        line-1: "&c&lPixelMOTD &7| Using &e1.16+ &7display!"
        line-2: "&fWe're on maintenance, please come back later."
      # Custom hover PER MOTD feature.
      # NOTE: Variables not supported right now.
      hover:
        toggle: false
        # Show players of an specific world in the hover.
        showCustomPlayers:
          # Toggle this option
          toggle: false
          # This world will be selected to show players.
          world: world
        # List of string message to display
        # on player count hover.
        message:
          - "&c&lPIXEL MOTD"
          - "&7&oWhitelist Mode"
          - ""
          - "&fDiscord support:"
          - "&brigox.club/discord/dev"
          - ""
          - "&7Please leave a &e⭐⭐⭐⭐⭐"
          - "&7star review!"
      # Use custom icon for your motd
      # Can set it on plugins/PixelMOTD/icons/whitelist/
      # MUST BE 64x64 icon.
      custom-icon:
        # Enable per-motd icon
        enable: false
        # If this option is enabled the plugin will create a new folder called "<mode>-<motdName>"
        # If you don't want use only 1 icon and you want more icons, you can use "RANDOM" in the name.
        name: "RANDOM"
    another:
      line-1: "         &c&l&k|||&a &lＭＩＮＥＶＩＥＴ.ＣＯＭ&a 1.8.x &6▲&4 1.17.x &c&l&k|||"
      line-2: "&c Máy chủ bảo trì! Vui lòng quay lại sau!"
      # ====================================================
      # HEX COLORS SUPPORT MISSING AT THE MOMENT.
      # ====================================================

      # Here you can use hex colors, if you don't need this
      # feature, you can disable this.
      # Only shows on 1.16 this motd, even if it doesn't have HEX colors.
      with-hex:
        enable: false
        line-1: "&b&lPixelMOTD &7| Using &e1.16+ &7display!"
        line-2: "&fWorking hard to bring up new updates."
      # Custom hover PER MOTD feature.
      # NOTE: Variables not supported right now.
      hover:
        toggle: false
        # Show players of an specific world in the hover.
        showCustomPlayers:
          # Toggle this option
          toggle: false
          # This world will be selected to show players.
          world: world
        # List of string message to display
        # on player count hover.
        message:
          - "&b&lPIXEL MOTD"
          - "&7&oWhitelist Mode"
          - ""
          - "&fDiscord support:"
          - "&brigox.club/discord/dev"
          - ""
          - "&7Please leave a &e⭐⭐⭐⭐⭐"
          - "&7star review!"
      # Use custom icon for your motd
      # Can set it on plugins/PixelMOTD/icons/whitelist/
      # MUST BE 64x64 icon.
      custom-icon:
        # Enable per-motd icon
        enable: false
        # If this option is enabled the plugin will create a new folder called "<mode>-<motdName>"
        # If you don't want use only 1 icon and you want more icons, you can use "RANDOM" in the name.
        name: "RANDOM"

outdated-client:
  # Use custom icon for Outdated-client MOTDs
  # Can set it on plugins/PixelMOTD/icons/outdatedClient/icon.png
  # MUST BE 64x64 icon.
  settings:
    icon: true
    # Custom Players Settings on online player count.
    custom-online:
      # Enable this option
      enable: false
      # Modes:
      # ADD-<number>,REMOVE-<number>, VALUES, ADD_MIDDLE, REMOVE_MIDDLE, EQUALS
      mode: 'ADD-450'
      # List of values:
      values:
        - 300
    # Custom Players Settings on max player count.
    custom-max:
      # Enable this option
      enable: false
      # Modes:
      # ADD-<number>,REMOVE-<number>, VALUES, ADD_MIDDLE, REMOVE_MIDDLE, EQUALS
      mode: 'EQUALS'
      # List of values:
      values:
        - 10000
    # Custom protocol settings on player count.
    custom-protocol:
      # Enable custom protocol.
      enable: true
      # If you want to change protocol when a player tries
      # to join on a incompatible version, keep it false.
      # Instead will display protocol name always.
      change-protocol-version:
        # Toggle this option
        toggle: false
        # Value of this protocol, protocol list: https://minecraft.fandom.com/wiki/Protocol_version
        # Show Incompatible version using '-1'
        value: '1000'
      # Custom protocol name to set if enabled.
      name: Outdated Client PixelMOTD
  #
  # MOTD FEATURE
  # You can add many motds as you want.
  # But always should be in this format:
  #
  #  first: # <--- CHANGE MOTD NAME, don't repeat it
  #    line-1: "message 1"
  #    line-2: "message 2"
  #    with-hex:
  #      enable: true
  #      line-1: "message 1"
  #      line-2: "message 2"
  #
  motds:
    first:
      line-1: "         &c&l&k|||&a &lＭＩＮＥＶＩＥＴ.ＣＯＭ&a 1.8.x &6▲&4 1.17.x &c&l&k|||"
      line-2: "&6&lFactionRPG &3| &9&lVillageDefense &3| &c&lCreative&c - và hơn nữa!"
      # ====================================================
      # HEX COLORS SUPPORT MISSING AT THE MOMENT.
      # ====================================================

      # Here you can use hex colors, if you don't need this
      # feature, you can disable this.
      # Only shows on 1.16 this motd, even if it doesn't have HEX colors.
      with-hex:
        enable: false
        line-1: "&c&lPixelMOTD &7| Using &e1.16+ &7display!"
        line-2: "&fInstall a most recent version of &cmc&f."
      # Custom hover PER MOTD feature.
      # NOTE: Variables not supported right now.
      hover:
        toggle: false
        # Show players of an specific world in the hover.
        showCustomPlayers:
          # Toggle this option
          toggle: false
          # This world will be selected to show players.
          world: world
        # List of string message to display
        # on player count hover.
        message:
          - "&c&lPIXEL MOTD"
          - "&7&oOutdated Client Mode"
          - ""
          - "&fDiscord support:"
          - "&brigox.club/discord/dev"
          - ""
          - "&7Please leave a &e⭐⭐⭐⭐⭐"
          - "&7star review!"
      # Use custom icon for your motd
      # Can set it on plugins/PixelMOTD/icons/outdatedClient/
      # MUST BE 64x64 icon.
      custom-icon:
        # Enable per-motd icon
        enable: false
        # If this option is enabled the plugin will create a new folder called "<mode>-<motdName>"
        # If you don't want use only 1 icon and you want more icons, you can use "RANDOM" in the name.
        name: "RANDOM"
    another:
      line-1: "         &c&l&k|||&a &lＭＩＮＥＶＩＥＴ.ＣＯＭ&a 1.8.x &6▲&4 1.17.x &c&l&k|||"
      line-2: "&6&lFactionRPG &3| &9&lVillageDefense &3| &c&lCreative&c - và hơn nữa!"
      # ====================================================
      # HEX COLORS SUPPORT MISSING AT THE MOMENT.
      # ====================================================

      # Here you can use hex colors, if you don't need this
      # feature, you can disable this.
      # Only shows on 1.16 this motd, even if it doesn't have HEX colors.
      with-hex:
        enable: false
        line-1: "&b&lPixelMOTD &7| Using &e1.16+ &7display!"
        line-2: "&6Install a new version of your minecraft."
      # Custom hover PER MOTD feature.
      # NOTE: Variables not supported right now.
      hover:
        toggle: false
        # Show players of an specific world in the hover.
        showCustomPlayers:
          # Toggle this option
          toggle: false
          # This world will be selected to show players.
          world: world
        # List of string message to display
        # on player count hover.
        message:
          - "&b&lPIXEL MOTD"
          - "&7&oOutdated Client Mode"
          - ""
          - "&fDiscord support:"
          - "&brigox.club/discord/dev"
          - ""
          - "&7Please leave a &e⭐⭐⭐⭐⭐"
          - "&7star review!"
      # Use custom icon for your motd
      # Can set it on plugins/PixelMOTD/icons/outdatedClient/
      # MUST BE 64x64 icon.
      custom-icon:
        # Enable per-motd icon
        enable: false
        # If this option is enabled the plugin will create a new folder called "<mode>-<motdName>"
        # If you don't want use only 1 icon and you want more icons, you can use "RANDOM" in the name.
        name: "RANDOM"

outdated-server:
  # Use custom icon for Outdated-client MOTDs
  # Can set it on plugins/PixelMOTD/icons/outdatedServer/icon.png
  # MUST BE 64x64 icon.
  settings:
    icon: true
    # Custom Players Settings on online player count.
    custom-online:
      # Enable this option
      enable: false
      # Modes:
      # ADD-<number>,REMOVE-<number>, VALUES, ADD_MIDDLE, REMOVE_MIDDLE, EQUALS
      mode: 'ADD-450'
      # List of values:
      values:
        - 300
    # Custom Players Settings on max player count.
    custom-max:
      # Enable this option
      enable: false
      # Modes:
      # ADD-<number>,REMOVE-<number>, VALUES, ADD_MIDDLE, REMOVE_MIDDLE, EQUALS
      mode: 'EQUALS'
      # List of values:
      values:
        - 10000
    # Custom protocol settings on player count.
    custom-protocol:
      # Enable custom protocol.
      enable: true
      # If you want to change protocol when a player tries
      # to join on a incompatible version, keep it false.
      # Instead will display protocol name always.
      change-protocol-version:
        # Toggle this option
        toggle: false
        # Value of this protocol, protocol list: https://minecraft.fandom.com/wiki/Protocol_version
        # Show Incompatible version using '-1'
        value: '-1'
      # Custom protocol name to set if enabled.
      name: Outdated Server PixelMOTD
  #
  # MOTD FEATURE
  # You can add many motds as you want.
  # But always should be in this format:
  #
  #  first: # <--- CHANGE MOTD NAME, don't repeat it
  #    line-1: "message 1"
  #    line-2: "message 2"
  #    with-hex:
  #      enable: true
  #      line-1: "message 1"
  #      line-2: "message 2"
  #
  motds:
    first:
      line-1: "         &c&l&k|||&a &lＭＩＮＥＶＩＥＴ.ＣＯＭ&a 1.8.x &6▲&4 1.17.x &c&l&k|||"
      line-2: "&6&lFactionRPG &3| &9&lVillageDefense &3| &c&lCreative&c - và hơn nữa!"
      # ====================================================
      # HEX COLORS SUPPORT MISSING AT THE MOMENT.
      # ====================================================

      # Here you can use hex colors, if you don't need this
      # feature, you can disable this.
      # Only shows on 1.16 this motd, even if it doesn't have HEX colors.
      with-hex:
        enable: false
        line-1: "&c&lPixelMOTD &7| Using &e1.16+ &7display!"
        line-2: "&fInstall an old version of &cmc&f."
      # Custom hover PER MOTD feature.
      # NOTE: Variables not supported right now.
      hover:
        toggle: false
        # Show players of an specific world in the hover.
        showCustomPlayers:
          # Toggle this option
          toggle: false
          # This world will be selected to show players.
          world: world
        # List of string message to display
        # on player count hover.
        message:
          - "&c&lPIXEL MOTD"
          - "&7&oOutdated Server Mode"
          - ""
          - "&fDiscord support:"
          - "&brigox.club/discord/dev"
          - ""
          - "&7Please leave a &e⭐⭐⭐⭐⭐"
          - "&7star review!"
      # Use custom icon for your motd
      # Can set it on plugins/PixelMOTD/icons/outdatedServer/
      # MUST BE 64x64 icon.
      custom-icon:
        # Enable per-motd icon
        enable: false
        # If this option is enabled the plugin will create a new folder called "<mode>-<motdName>"
        # If you don't want use only 1 icon and you want more icons, you can use "RANDOM" in the name.
        name: "RANDOM"
    another:
      line-1: "         &c&l&k|||&a &lＭＩＮＥＶＩＥＴ.ＣＯＭ&a 1.8.x &6▲&4 1.17.x &c&l&k|||"
      line-2: "&6&lFactionRPG &3| &9&lVillageDefense &3| &c&lCreative&c - và hơn nữa!"
      # ====================================================
      # HEX COLORS SUPPORT MISSING AT THE MOMENT.
      # ====================================================

      # Here you can use hex colors, if you don't need this
      # feature, you can disable this.
      # Only shows on 1.16+ this motd, even if it doesn't have HEX colors.
      with-hex:
        enable: true
        line-1: "&b&lPixelMOTD &7| Using &e1.16+ &7display!"
        line-2: "&6Install an old version of your minecraft."
      # Custom hover PER MOTD feature.
      # NOTE: Variables not supported right now.
      hover:
        toggle: false
        # Show players of an specific world in the hover.
        showCustomPlayers:
          # Toggle this option
          toggle: false
          # This world will be selected to show players.
          world: world
        # List of string message to display
        # on player count hover.
        message:
          - "&b&lPIXEL MOTD"
          - "&7&oOutdated Server Mode"
          - ""
          - "&fDiscord support:"
          - "&brigox.club/discord/dev"
          - ""
          - "&7Please leave a &e⭐⭐⭐⭐⭐"
          - "&7star review!"
      # Use custom icon for your motd
      # Can set it on plugins/PixelMOTD/icons/outdatedServer/
      # MUST BE 64x64 icon.
      custom-icon:
        # Enable per-motd icon
        enable: false
        # If this option is enabled the plugin will create a new folder called "<mode>-<motdName>"
        # If you don't want use only 1 icon and you want more icons, you can use "RANDOM" in the name.
        name: "RANDOM"

**Comment by CreeperboyMCVN** [comment]
idk but the file from the older version, if that's the reason make the plugin buggy can u make something like config-version :v

**Comment by MrUniverse44** [comment]
The bug here was the version, this motds.yml was from an older version and the new motds.yml was reworked w/ different paths and new options, so i will add a config-version for a notification system.
